Symfony/src/Entity/Character.php
<?php

namespace App\Entity;

use App\Repository\AttackRepository;
use App\Repository\CharacterRepository;
use App\Repository\DungeonRepository;
use App\Repository\RaidRepository;
use App\Repository\TypeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Table;
use Exception;
use Symfony\Contracts\Translation\TranslatorInterface;

#[ORM\Entity(repositoryClass: CharacterRepository::class)]
#[Table(name: '`character`')]
class Character
{
    public const GENDER_MALE = 'Mâle';
    public const GENDER_FEMALE = 'Femelle';
    public const MIN_AGE = 18;
    public const MAX_AGE = 44;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(name: '`name`',length: 30)]
    private ?string $name = null;

    #[ORM\Column(name: '`gender`',length: 10)]
    private ?string $gender = null;

    #[ORM\Column(name: '`age`')]
    private ?int $age = null;

    #[ORM\Column(name: '`description`', length: 200, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(name: '`level`')]
    public ?int $level = 0;

    #[ORM\Column(name: '`xp`')]
    public ?int $xp = 0;

    #[ORM\OneToOne(mappedBy: 'Character', cascade: ['persist', 'remove'])]
    private ?User $userI = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Stats $Stats = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Gear $Gear = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Inventory $Inventory = null;

    #[ORM\ManyToOne(inversedBy: 'Characters')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Species $Species = null;

    #[ORM\ManyToMany(targetEntity: CombatLog::class, mappedBy: 'Characters')]
    private Collection $CombatLogs;

    #[ORM\OneToMany(mappedBy: 'Character', targetEntity: Rotation::class)]
    private Collection $rotations;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Timers $Timers = null;

    #[ORM\Column]
    private ?bool $isShiny = null;

    #[ORM\ManyToOne(inversedBy: 'Explorers')]
    private ?DungeonInstance $currentExplorationDungeonInstance = null;

    #[ORM\ManyToOne(inversedBy: 'Explorers')]
    private ?RaidInstance $currentExplorationRaidInstance = null;

    public function __construct()
    {
        $this->CombatLogs = new ArrayCollection();
        $this->rotations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUserI(): ?User
    {
        return $this->userI;
    }

    public function setUserI(?User $userI): self
    {
        // unset the owning side of the relation if necessary
        if ($userI === null && $this->userI !== null) {
            $this->userI->setCharacter(null);
        }

        // set the owning side of the relation if necessary
        if ($userI !== null && $userI->getCharacter() !== $this) {
            $userI->setCharacter($this);
        }

        $this->userI = $userI;

        return $this;
    }

    public function getStats(): ?Stats
    {
        return $this->Stats;
    }

    public function setStats(?Stats $Stats): self
    {
        $this->Stats = $Stats;

        return $this;
    }

    public function getGear(): ?Gear
    {
        return $this->Gear;
    }

    public function setGear(?Gear $Gear): self
    {
        $this->Gear = $Gear;

        return $this;
    }

    public function getInventory(): ?Inventory
    {
        return $this->Inventory;
    }

    public function setInventory(?Inventory $Inventory): self
    {
        $this->Inventory = $Inventory;

        return $this;
    }

    public function getSpecies(): ?Species
    {
        return $this->Species;
    }

    public function setSpecies(?Species $Species): self
    {
        $this->Species = $Species;

        return $this;
    }

    /**
     * @return Collection<int, CombatLog>
     */
    public function getCombatLogs(): Collection
    {
        return $this->CombatLogs;
    }

    public function getLastTenCombatLogs(): array
    {
        $combatLogs = $this->CombatLogs->toArray();

        usort($combatLogs, function($a, $b){
            return $b->getDateCreation()->getTimestamp() - $a->getDateCreation()->getTimestamp();
        });

        return array_slice($combatLogs, 0, 10);
    }
    
    public function addCombatLog(CombatLog $combatLog): self
    {
        if (!$this->CombatLogs->contains($combatLog)) {
            $this->CombatLogs->add($combatLog);
            $combatLog->addCharacter($this);
        }

        return $this;
    }

    public function removeCombatLog(CombatLog $combatLog): self
    {
        if ($this->CombatLogs->removeElement($combatLog)) {
            $combatLog->removeCharacter($this);
        }

        return $this;
    }
    
    public function getCurrentExplorationDungeonInstance(): ?DungeonInstance
    {
        return $this->currentExplorationDungeonInstance;
    }

    public function setCurrentExplorationDungeonInstance(?DungeonInstance $currentExplorationDungeonInstance): self
    {
        $this->currentExplorationDungeonInstance = $currentExplorationDungeonInstance;

        return $this;
    }

    public function getTimers(): ?Timers
    {
        return $this->Timers;
    }

    public function setTimers(Timers $Timers): self
    {
        $this->Timers = $Timers;

        return $this;
    }

    public function isShiny(): ?bool
    {
        return $this->isShiny;
    }

    public function setIsShiny(bool $isShiny): self
    {
        $this->isShiny = $isShiny;

        return $this;
    }

    public function getCurrentExplorationRaidInstance(): ?RaidInstance
    {
        return $this->currentExplorationRaidInstance;
    }

    public function setCurrentExplorationRaidInstance(?RaidInstance $currentExplorationRaidInstance): self
    {
        $this->currentExplorationRaidInstance = $currentExplorationRaidInstance;

        return $this;
    }

    /* -------------------------------------------------------------------------- */
    /*                                  SHORTCUTS                                 */
    /* -------------------------------------------------------------------------- */

    public function getLevel(): ?int
    {
        return $this->Stats->getLevel();
    }

    public function getXp(): ?int
    {
        
        return $this->Stats->getXp();
    }

    public function getTypes(): array
    {
        $speciesType = $this->getSpecies()->getType();

        return $speciesType->toArray();
    }

    /* -------------------------------------------------------------------------- */
    /*                                 XP & LEVELS                                */
    /* -------------------------------------------------------------------------- */

    public function gainXp($xpAmount): void
    {
        $this->Stats->gainXp($xpAmount);
    }

    public function getXPCeil(): int
    {
        return $this->Stats->getXPCeil();
    }

    public function getXPPercentage(): int
    {
        return $this->Stats->getXPPercentage();
    }

    /* -------------------------------------------------------------------------- */
    /*                             Rotations & Opener                             */
    /* -------------------------------------------------------------------------- */

    /**
     * @return Collection<int, Rotation>
     */
    public function getRotations(): Collection
    {
        return $this->rotations;
    }

    /**
     * @return Rotation|null
     */
    public function getRotation(): ?Rotation
    {
        foreach ($this->rotations as $rotation) {
            if($rotation->getType() === Rotation::TYPE_ROTATION){
                return $rotation;
            }
        }

        return null;
    }

    /**
     * @return Rotation|null
     */
    public function getOpenerRotation(): ?Rotation
    {
        foreach ($this->rotations as $rotation) {
            if($rotation->getType() === Rotation::TYPE_OPENER){
                return $rotation;
            }
        }

        return null;
    }

    /**
     * Returns in a array all the Attacks available for a character
     */
    public function getAvailableAttacks(TypeRepository $typeRepository, AttackRepository $attackRepository): array
    {
        $adventurerType = $typeRepository->findOneBy(['name' => 'Aventurier']);

        $allCharacterAttackTypes = [$adventurerType];

        foreach ($this->getTypes() as $type) {
            $allCharacterAttackTypes[] = $type;
        }

        $attackList = [];
        foreach ($allCharacterAttackTypes as $type) {
            foreach ($attackRepository->findAvailableAttacksForLevelAndType($this->getLevel(), $type) as $attack) {
                $attackList[] = $attack;
            }
        }
        
        return $attackList;
    }

    /* -------------------------------------------------------------------------- */

Symfony/src/Controller/RaidController.php
<?php

namespace App\Controller;

use App\Entity\RaidInstance;
use App\Entity\User;
use App\Form\CreateRaidInstanceType;
use App\Form\JoinRaidInstanceType;
use App\Repository\AttackRepository;
use App\Repository\RaidInstanceRepository;
use App\Repository\RaidRepository;
use App\Service\Raid\RaidDataManager;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Contracts\Translation\TranslatorInterface;

class RaidController extends AbstractController
{
    #[IsGranted('ROLE_USER')]
    #[Route('/jeu/raid', name: 'app_raid')]
    public function raid(Request $request, RaidDataManager $raidDataManager, RaidInstanceRepository $raidInstanceRepository, EntityManagerInterface $em): Response
    {
        $user = $this->getUser();
        $raidInstance = $user->getCharacter()->getCurrentExplorationRaidInstance();

        $joinRaidInstanceForm = $this->createForm(JoinRaidInstanceType::class);

        $joinRaidInstanceForm->handleRequest($request);

        if($joinRaidInstanceForm->isSubmitted() && $joinRaidInstanceForm->isValid() && $user->getCharacter()->getTimers()->getRaidCharges() > 0){
            $formData = $joinRaidInstanceForm->getData();

            $raidInstance = $raidInstanceRepository->findOneBy(['inviteCode' => $formData['inviteCode']]);

            if($raidInstance !== null){
                $raidInstance->addExplorer($user->getCharacter());

                $em->flush();
                return $this->redirectToRoute('app_raid');
            }
        }

        if($raidInstance !== null){
            $raidDataManager->setRaidId($raidInstance->getRaid()->getId());
        }

        return $this->render('Raid/raid.html.twig', [
            'raidInstance' => $raidInstance,
            'raidDataManager' => $raidDataManager,
            'joinRaidInstanceView' => $joinRaidInstanceForm->createView()
        ]);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/jeu/raid/create', name: 'app_raid_create')]
    public function create(Request $request, RaidRepository $raidRepository, RaidInstanceRepository $raidInstanceRepository, TranslatorInterface $translator, EntityManagerInterface $em): Response
    {
        $user = $this->getUser();
        $character = $user->getCharacter();

        if(!$character->getTimers()->getRaidCharges() > 0){
            return $this->redirectToRoute('app_raid');
        }

        $raidInstanceCreateForm = $this->createForm(CreateRaidInstanceType::class, null, [
            'character' => $user->getCharacter(),
            'raidRepository' => $raidRepository,
            'translator' => $translator
        ]);

        $raidInstanceCreateForm->handleRequest($request);

        if($raidInstanceCreateForm->isSubmitted() && $raidInstanceCreateForm->isValid()){
            $formData = $raidInstanceCreateForm->getData();

            $raidInstance = new RaidInstance();
            $raidInstance->setDateCreated(new DateTime())
                         ->setRaid($formData['Raid'])
                         ->setCurrentExplorersRoom(0)
                         ->setLeader($character)
                         ->addExplorer($character)
                         ->setStatus(RaidInstance::RAID_STATUS_PREPARATION)
                         ->generateRandomInviteCode($raidInstanceRepository);
            
            $em->persist($raidInstance);
            $em->flush();

            return $this->redirectToRoute('app_raid');
        }

        return $this->render('Raid/raid-create.html.twig', [
            'raidInstanceCreateFormView' => $raidInstanceCreateForm->createView()
        ]);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/jeu/raid/instance/{id}/enter', name: 'app_raid_instance_enter')]
    public function enterInstance($id, RaidInstanceRepository $raidInstanceRepository, EntityManagerInterface $em): JsonResponse
    {
        $raidInstance = $raidInstanceRepository->find($id);

        if($raidInstance === null){
            return new JsonResponse([
                'message' => 'Instance non valide.'
            ], 400);
        }

        $user = $this->getUser();

        if(!$this->hasCharacterInRaid($user, $raidInstance) || $user->getCharacter() !== $raidInstance->getLeader()){
            return new JsonResponse([
                'message' => 'Accès non-autorisé.'
            ], 400);
        }

        if($raidInstance->getStatus() !== RaidInstance::RAID_STATUS_PREPARATION){
            return new JsonResponse([
                'message' => "Vous n'êtes pas en préparation"
            ], 400);
        }

        $raidInstance->explorerEnterRaid($em);

        return new JsonResponse([
            'message' => 'Vous êtes bien entré dans le raid.'
        ], 200);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/jeu/raid/instance/{id}/leave', name: 'app_raid_instance_leave')]
    public function leaveInstance($id, RaidInstanceRepository $raidInstanceRepository, EntityManagerInterface $em): JsonResponse
    {
        $raidInstance = $raidInstanceRepository->find($id);
    
        if($raidInstance === null){
            return new JsonResponse([
                'message' => 'Instance non valide.'
            ], 400);
        }

        $user = $this->getUser();

        if(!$this->hasCharacterInRaid($user, $raidInstance)){
            return new JsonResponse([
                'message' => 'Accès non-autorisé.'
            ], 400);
        }

        $raidInstance->explorerLeaveRaid($user->getCharacter(), $em);

        $em->flush();

        return new JsonResponse([
            'message' => 'Vous avez bien quitté le donjon.'
        ], 200);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/jeu/raid/instance/{id}/fight', name: 'app_raid_instance_fight')]
    public function fightMonsterInstance($id, RaidInstanceRepository $raidInstanceRepository, AttackRepository $attackRepository, RaidDataManager $raidDataManager, EntityManagerInterface $em): JsonResponse
    {
        $raidInstance = $raidInstanceRepository->find($id);
    
        if($raidInstance === null){
            return new JsonResponse([
                'message' => 'Instance non valide.'
            ], 400);
        }

        $user = $this->getUser();

        if(!$this->hasCharacterInRaid($user, $raidInstance)){
            return new JsonResponse([
                'message' => 'Accès non-autorisé.'
            ], 400);
        }

        if($raidInstance->getStatus() !== RaidInstance::RAID_STATUS_EXPLORATION){
            return new JsonResponse([
                'message' => "Vous n'êtes pas en exploration"
            ], 400);
        }

        $raidDataManager->setRaidId($raidInstance->getRaid()->getId());
        $raidInstance->explorerFightMonsters($em, $attackRepository, $raidDataManager);
        
        return new JsonResponse([
            'message' => 'Vous avez bien combattu les monstres.'
        ], 200);
    }

    /* -------------------------------------------------------------------------- */
    /*                              SERVICE FUNCTIONS                             */
    /* -------------------------------------------------------------------------- */

    private function hasCharacterInRaid(User $user, RaidInstance $raidInstance): bool
    {
        $character = $user->getCharacter();

        if(in_array($character, $raidInstance->getExplorers())){
            return true;
        }

        return false;
    }
}

Symfony/templates/Raid/raid-create.html.twig
{% extends 'base.html.twig' %}

{% block title %}PMD : Valtoria | Raid{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/raid/app_raid_create.css') }}">
{% endblock %}

{% block body %}
    <div class="raidCreateTitle">{{ 'quel_raid_voulez_vous_explorer'|trans({}, 'app') }}</div>
    {{ form_start(raidInstanceCreateFormView, {'attr': {'class': 'raidCreate_form'}}) }}
        {{ form_widget(raidInstanceCreateFormView.Raid, {'attr': {'class': 'raidCreate_formWidget'}}) }}
        {{ form_widget(raidInstanceCreateFormView.submit, {'attr': {'class': 'raidCreate_Submit'}}) }}
    {{ form_end(raidInstanceCreateFormView) }}
{% endblock %}

Symfony/templates/Raid/raid.html.twig
{% extends 'base.html.twig' %}

{% block title %}PMD : Valtoria | Raid{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/raid/app_raid.css') }}">
    <link rel="stylesheet" href="{{ asset('css/_shared/_character-card.css') }}">
{% endblock %}

{% block body %}
    {% if raidInstance is not null %}
        {% include "Raid/_raid-show.html.twig" %}
    {% else %}
        <div class="noRaidImage"><img src="{{ asset('images/evoli-sleep.png') }}" alt="Evoli qui dort"></div>
        <div class="noRaidTitle">{{ 'vous_etes_dans_aucun_raid'|trans({}, 'app') }}</div>

        {% if app.user.character.timers.getCooldownRaidTime() is not null %}
            <div class="noRaidCooldownTimerContainer">
                <p>{{ 'temps_de_recuperation_avant_la_prochaine_charge'|trans({}, 'app') }}</p>
                <div id="noRaidCooldownTimer">-</div>  
            </div>
        {% endif %}

        {% if app.user.character.timers.getRaidCharges() > 0 %}
            <div class="noRaidChargesNumber">{{ 'charge_de_raid_actuelle'|trans({}, 'app') }} {{ app.user.character.timers.getRaidCharges() }} / {{ constant('App\\Entity\\Timers::MAX_RAID_CHARGES') }}</div>
            <a class="noRaidCreateRaidInstanceLink" href="{{ path('app_raid_create') }}">
                <div class="noRaidCreateRaidInstance">{{ 'creer_un_groupe_exploration'|trans({}, 'app') }}</div>
            </a>
            
            <div class="joinRaidInstanceSeparator"></div>

            <div class="joinRaidInstanceTitle">{{ 'un_groupe_vous_attends_rejoignez_le'|trans({}, 'app') }}</div>

            {{ form_start(joinRaidInstanceView, {'attr': {'class': 'raidInstanceJoin_form'}}) }}
                <div class="joinInviteCodePannel">
                    <div class="joinInviteCodePannelTitle">{{ 'code_invitation'|trans({}, 'app') }}</div>
                    {{ form_widget(joinRaidInstanceView.inviteCode, {'attr': {'class': 'raidInstanceJoin_formWidget joinInviteCodePannelContent'}}) }}
                </div>
            {{ form_end(joinRaidInstanceView) }}
        {% endif %}
    {% endif %}
    
{% endblock %}

{% block javascripts %}
    {% if raidInstance is not null %}
        <script>
            function sendEnterRaidCall(){
                let urlToCall = "{{ path('app_raid_instance_enter', {'id' : raidInstance.id}) }}";

                fetch(urlToCall).then(function(response){
                    if(response.status === 200){
                        location.reload();
                    }
                    else if(response.status === 400){
                        response.json().then(function(jsonData){
                            errorMessages.innerHTML = jsonData.message
                        });
                    }
                })
            }

            function sendLeaveRaidCall(){
                let urlToCall = "{{ path('app_raid_instance_leave', {'id' : raidInstance.id}) }}";

                fetch(urlToCall).then(function(response){
                    if(response.status === 200){
                        location.reload();
                    }
                    else if(response.status === 400){
                        response.json().then(function(jsonData){
                            errorMessages.innerHTML = jsonData.message
                        });
                    }
                })
            }

            function sendFightRaidCall(){
                let urlToCall = "{{ path('app_raid_instance_fight', {'id' : raidInstance.id}) }}";

                fetch(urlToCall).then(function(response){
                    if(response.status === 200){
                        location.reload();
                    }
                    else if(response.status === 400){
                        response.json().then(function(jsonData){
                            errorMessages.innerHTML = jsonData.message
                        });
                    }
                })
            }
        </script>
    {% endif %}

    {% if app.user.character.timers.getCooldownRaidTime() is not null and raidInstance is null %}
        <script>
            var month = {{app.user.character.timers.getCooldownRaidTime()|date("m")}}-1;
            var countDownDate = new Date({{app.user.character.timers.getCooldownRaidTime()|date("Y,")}} month, {{app.user.character.timers.getCooldownRaidTime()|date("d,H,i,s")}});

            // Update the count down every 1 second 
            var x = setInterval(function() {

            // Get today's date and time
            var now = new Date().getTime();

            // Find the distance between now and the count down date
            var distance = countDownDate - now;

            // Time calculations for days, hours, minutes and seconds
            var days = Math.floor(distance / (1000 * 60 * 60 * 24));
            var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((distance % (1000 * 60)) / 1000);

            // Display the result in the element with id="demo"
            document.getElementById("noRaidCooldownTimer").innerHTML = days + "j " + hours + "h " + minutes + "m " + seconds + "s ";

            // If the count down is finished, write some text
            if (distance < 0) {
                clearInterval(x);
                document.getElementById("noRaidCooldownTimer").innerHTML = "Prêt !";
                window.location.reload();
            }
            }, 1000);
        </script>
    {% endif %}
{% endblock %}