Symfony/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $discordTag = null;

    #[ORM\Column(type: 'json', nullable: true)]
    private ?array $roles = ['ROLE_USER'];

    #[ORM\OneToOne(inversedBy: 'userI', cascade: ['persist', 'remove'])]
    private ?Character $Character = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $username = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $accessToken = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDiscordTag(): ?string
    {
        return $this->discordTag;
    }

    public function setDiscordTag(string $discordTag): self
    {
        $this->discordTag = $discordTag;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function addRoles(array $roles): self
    {
        foreach ($roles as $role) {
            $this->roles[] = $role;
        }

        return $this;
    }

    public function getCharacter(): ?Character
    {
        return $this->Character;
    }

    public function setCharacter(?Character $Character): self
    {
        $this->Character = $Character;

        return $this;
    }

    /**
     * The public representation of the user (e.g. a username, an email address, etc.)
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->discordTag.$this->email;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getAccessToken(): ?string
    {
        return $this->accessToken;
    }

    public function setAccessToken(?string $accessToken): self
    {
        $this->accessToken = $accessToken;

        return $this;
    }
}

Symfony/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
        <title>{% block title %}PMD : Valtoria{% endblock %}</title>
        <link rel="icon" href="{{ asset('icons/valtoria.png') }}">

        <link rel="stylesheet" href="{{ asset('base.css') }}">
        {% block stylesheets %}{% endblock %}
        {% trans_default_domain 'app' %}
    </head>
    <body>
        {% include '_shared/_navbar.html.twig' %}

        <div class="flashMessagesContainer">
            {% set flashMessagesCounter = 0 %}
            {% for message in app.flashes('success') %}
                <div id='js-flash-{{flashMessagesCounter}}' class="flashMessage flashSuccess">
                    <div class="flashMessageCloseButton">
                        <div onClick="closeFlashMessage('js-flash-{{flashMessagesCounter}}')">X</div>
                    </div>
                    <span class="flashMessageContent">{{ message }}</span>
                </div>
                {% set flashMessagesCounter = flashMessagesCounter + 1 %}
            {% endfor %}
            {% for message in app.flashes('danger') %}
                <div id='js-flash-{{flashMessagesCounter}}' class="flashMessage flashWarning">
                    <div class="flashMessageCloseButton">
                        <div onClick="closeFlashMessage('js-flash-{{flashMessagesCounter}}')">X</div>
                    </div>
                    <span class="flashMessageContent">{{ message }}</span>
                </div>
                {% set flashMessagesCounter = flashMessagesCounter + 1 %}
            {% endfor %}
        </div>

        {% if app.user %}
            {% if app.user.character == null %}
                <a class="playButton" href="{{ path('app_character_create') }}">{{ 'jouer'|trans({}, 'app') }}</a>
            {% else %}
                <a class="playButton" href="{{ path('app_hub') }}">{{ 'guilde'|trans({}, 'app') }}</a>
            {% endif %}
        {% endif %}
        <div id='content'>
            {% block body %}{% endblock %}
        </div>
        {% include "_shared/_flash-message.html.twig" %}
        {% block javascripts %}{% endblock %}
        <footer>
            <p>{{ 'footer_description'|trans({}, 'app') }}</p>
        </footer>
    </body>
</html>

Symfony/templates/dungeon.html.twig
{% extends "base.html.twig" %}

{% block title %}PDM : Valtoria | Dungeon Preview {% endblock %}

{% block body %}
    <h1 style='margin-bottom: 3px'>{{ dungeonInstance.dungeon.name }}</h1>
    
    <h2 style='text-align:center; margin-top:0;'>Statut : {{ dungeonInstance.status|DungeonInstanceStatus }}</h2>

    {% if dungeonInstance.status == 'dungeon_status_preparation'%}
        <div style='text-align:center; font-size:22px; font-style: italic;'>Votre équipe se prépare à entrer dans le donjon.</div>
        <hr>
        <h2 style='text-align:center; margin-bottom: 0;'>Composition de l'équipe</h2>
        <h2 style='text-align:center; margin-top:0; font-size: 20px'>{{dungeonInstance.explorers|length}}/4 aventuriers</h2>
        <div class="dungeon-preparation-character-container">
            {% for character in dungeonInstance.explorers %}
                {% include '_shared/_character-card.html.twig' %}
            {% endfor %}
        </div>

        <div style="display:flex;justify-content:center;">
            <button onclick="sendEnterDungeonCall()" class="dungeonButton buttonEnterDungeon">Entrer dans le donjon</button>
        </div>
        <div style="margin-top:20px" class="dungeonEndingButton">
            <button onclick="sendLeaveApiCall()" class="dungeonButton ButtonLeave"><img src="{{ asset('icons/exit.png') }}" width='25px'></button>
        </div>
        <div class="dungeonErrorMessages"></div>
    {% else %}
        <div class="dungeonGame">
            <div class="dungeonTips">
                <div class="dungeonTipsRow">
                    <div class="tile-tip tile-unknown"></div>
                    <div class="tile-tip-text">Pièce inconnue du donjon, que contient-elle ?</div>
                </div>
                <div class="dungeonTipsRow">
                    <div class="tile-tip tile-empty"></div>
                    <div class="tile-tip-text">Ceci est un mur, vous ne pouvez vous y rendre.</div>
                </div>
                <div class="dungeonTipsRow">
                    <div class="tile-tip tile-full"></div>
                    <div class="tile-tip-text">Pièce vide du donjon, passez votre chemin.</div>
                </div>
                <div class="dungeonTipsRow">
                    <div class="tile-tip tile-entrance"></div>
                    <div class="tile-tip-text">Entrée du donjon.</div>
                </div>
                <div class="dungeonTipsRow">
                    <div class="tile-tip tile-exit"></div>
                    <div class="tile-tip-text">Sortie du donjon.</div>
                </div>
                <div class="dungeonTipsRow" style="margin-bottom : 10px">
                    <div class="tile-tip tile-monsters-1" style="margin-right: 2px"></div>
                    <div class="tile-tip tile-monsters-2" style="margin-right: 2px"></div>
                    <div class="tile-tip tile-monsters-3"></div>
                    <div class="tile-tip-text">Pokémon(s) sauvage(s) en vue !</div>
                </div>
                <div class="dungeonTipsSeparator"></div>
                <div class="dungeonTipsNotes">
                    <div class="dungeonTipsNotesTitle">Notes</div>
                    <ul>
                        <li>Pour compléter le donjon, vous devez trouver la sortie et sortir.</li>
                        <li>Vous ne pouvez pas vous enfuir d'une case contenant un/des pokémon(s) sauvage(s)</li>
                    </ul>
                </div>
            </div>
            <div class="dungeon">
                {% for y in data.maxY .. data.minY %}
                    <div class="dungeon-row">
                        {% for x in data.minX .. data.maxX %}
                            {% set tilePos = y ~ ',' ~ x %}
                                <div title='{{ tilePos }}' class="{{ dungeon[tilePos] |dungeonTile(currentExplorersPosition, tilePos) }}"></div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
            <div style="width: 33%; margin-top: -10px">
                <div class="dungeonExplorersList">
                    {% for character in dungeonInstance.explorers %}
                        {% include '_shared/_character-card.html.twig' %}
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="dungeonButtons">
            {% if dungeonInstance.status == 'dungeon_status_exploration' %}
                <div class="dungeonDirectionButtons">
                    <button onclick="sendMovementApiCall('left')" class="dungeonButton"><img src="{{ asset('icons/arrow_left.png') }}" width='25px'></button>
                    <button onclick="sendMovementApiCall('up')" class="dungeonButton"><img src="{{ asset('icons/arrow_up.png') }}" width='20px'></button>
                    <button onclick="sendMovementApiCall('down')" class="dungeonButton"><img src="{{ asset('icons/arrow_down.png') }}" width='20px'></button>
                    <button onclick="sendMovementApiCall('right')" class="dungeonButton"><img src="{{ asset('icons/arrow_right.png') }}" width='25px'></button>
                </div>
                <div class="dungeonInteractionButtons">
                    <button onclick="sendFightApiCall()" class="dungeonButton ButtonFight"><img src="{{ asset('icons/dual-swords.svg') }}" width='28px'></button>
                    <button onclick="sendInteractApiCall()" class="dungeonButton ButtonInteract"><img src="{{ asset('icons/hand.png') }}" width='28px'></button>
                </div>
            {% else %}
                <div class="dungeonEndingButton">
                    <button onclick="sendLeaveApiCall()" class="dungeonButton ButtonLeave"><img src="{{ asset('icons/exit.png') }}" width='25px'></button>
                </div>
            {% endif %}
        </div>

        <div class="dungeonErrorMessages"></div>

        <div style='display:flex; justify-content: space-around; margin-top:20px'>
            <div class="dungeonFightsLogs">
                <div class="dungeonFightsLogsTitle">Liste des combats</div>
                <div class="dungeonFightsLogsSeparator"></div>
                <div class="dungeonFightsLogsList">
                    <ul>
                        {% for fightLog in dungeonInstance.Fights|reverse %}
                            {% if fightLog.winner == 1 %}
                                <li class="dungeonFightsLogsListLiVictory">
                            {% else %}
                                <li class="dungeonFightsLogsListLiDefeat">
                            {% endif %}
                                    <a href="{{ path('app_combat', {'id' : fightLog.id }) }}" style='display:flex; align-items:center;'>
                                        {% if fightLog.winner == 1 %}
                                            <span style='margin-right:5px; color: rgb(2, 188, 2);'>[VICTOIRE]</span> {{ fightLog.teamTwo|length }} Pokémons sauvages vaincus ({{fightLog.message}})
                                        {% else %}
                                            <span style='margin-right:5px; color:red;'>[DÉFAITE]</span> Votre équipe a été vaincu. ({{fightLog.message}})
                                        {% endif %}
                                        <img src="{{ asset('icons/oeil.png') }}" width=25 height=25 alt="">
                                    </a>
                                </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div style='width: 550px'></div>
            <div style='width: 550px'></div>
        </div>
    {% endif %}
    


    <div class="no-footer"></div>

    <script>
        const directionButtons = document.querySelectorAll("[data-direction]");
        var errorMessages = document.getElementsByClassName('dungeonErrorMessages')[0];

        function sendMovementApiCall(direction){
            let urlToCall = "{{ path('app_dungeon_instance_move', {'id' : dungeonInstance.id, 'direction' : 'DIRECTION'}) }}";
            urlToCall = urlToCall.replace('DIRECTION', direction);
            
            fetch(urlToCall).then(function(response) {
                if(response.status === 200){
                    location.reload();
                }
                else if(response.status === 400){
                    response.json().then(function(jsonData){
                        errorMessages.innerHTML = jsonData.message
                    });
                }
            });
        }

        function sendFightApiCall(){
            let urlToCall = "{{ path('app_dungeon_instance_fight', {'id' : dungeonInstance.id}) }}";

            fetch(urlToCall).then(function(response){
                if(response.status === 200){
                    location.reload();
                }
                else if(response.status === 400){
                    response.json().then(function(jsonData){
                        errorMessages.innerHTML = jsonData.message
                    });
                }
            })
        }

        function sendEnterDungeonCall(){
            let urlToCall = "{{ path('app_dungeon_instance_enter', {'id' : dungeonInstance.id}) }}";

            fetch(urlToCall).then(function(response){
                if(response.status === 200){
                    location.reload();
                }
                else if(response.status === 400){
                    response.json().then(function(jsonData){
                        errorMessages.innerHTML = jsonData.message
                    });
                }
            })
        }

        function sendInteractApiCall(){
            let urlToCall = "{{ path('app_dungeon_instance_interact', {'id' : dungeonInstance.id}) }}";

            fetch(urlToCall).then(function(response){
                if(response.status === 200){
                    location.reload();
                }
                else if(response.status === 400){
                    response.json().then(function(jsonData){
                        errorMessages.innerHTML = jsonData.message
                    });
                }
            })
        }

        function sendLeaveApiCall(){
            let urlToCall = "{{ path('app_dungeon_instance_leave', {'id' : dungeonInstance.id}) }}";

            fetch(urlToCall).then(function(response){
                if(response.status === 200){
                    location.reload();
                }
                else if(response.status === 400){
                    response.json().then(function(jsonData){
                        errorMessages.innerHTML = jsonData.message
                    });
                }
            })
        }
    </script>
{% endblock %}

Symfony/templates/home.html.twig
{% extends "base.html.twig" %}

{% block title %}PMD : Valtoria{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/app_home.css') }}">
{% endblock %}
{% block body %}
    <div class="homePresentation">
        <div class="homePresentationBoard">
            <div class="gameResume">
                <div class="mysteryDungeonIcon"><img src="{{ asset('images/mystery-dungeon-icon.png') }}" alt="Icone de donjon mystère"></div>
                <div>{{ 'valtoria_game_resume'|trans({}, 'app') }}</div>
            </div>
            <div class="separator"></div>
            <div class="gameRpResume">
                <div class="gameRpResumeText1">
                    {{ 'valtoria_game_rp_resume_1'|trans({}, 'app') }}
                </div>
                <div class="gameRpResumeText2">
                    {{ 'valtoria_game_rp_resume_2'|trans({}, 'app') }}
                </div>
            </div>
        </div>
        <div class="homePresentationRightPannel">
            <div class="explorersImage"><img src="{{ asset('images/explorers-group.png') }}" alt="Équipe d'explorateurs Pokémon"></div>
        </div>
    </div>

    <div class="separator"></div>

    <div class="homeTeam">
        <div class="homeTeamTopPannel">
            <div class="homeTeamTopPannelImage"><img src="{{ asset('images/three-explorers.png') }}" alt="Trois aventuriers"></div>
            <div class="homeTeamTopPannelText">{{ 'faites_equipe_avec_vos_amis'|trans({}, 'app') }}</div>
        </div>
        <div class="homeTeamBottomPannel">
            <div class="homeTeamBottomPannelCard">
                <div class="homeTeamBottomPannelCardTopPannel">
                    <div class="homeTeamBottomPannelCardTopPannelImage"><img src="{{ asset('images/fighting-riolu.png') }}" alt="Riolu combattant"></div>
                    <div class="homeTeamBottomPannelCardTopPannelTitle">{{ 'infligez_des_degats'|trans({}, 'app') }}</div>
                </div>
                <div class="homeTeamBottomPannelCardBottomPannel">{{ 'infligez_des_degats_description'|trans({}, 'app') }}</div>
            </div>
            <div class="homeTeamBottomPannelDivider"></div>
            <div class="homeTeamBottomPannelCard">
                <div class="homeTeamBottomPannelCardTopPannel">
                    <div class="homeTeamBottomPannelCardTopPannelImage"><img src="{{ asset('images/carapuce-protecteur.png') }}" alt="Riolu combattant"></div>
                    <div class="homeTeamBottomPannelCardTopPannelTitle">{{ 'protegez_vos_allies'|trans({}, 'app') }}</div>
                </div>
                <div class="homeTeamBottomPannelCardBottomPannel">{{ 'protegez_vos_allies_description'|trans({}, 'app') }}</div>
            </div>
            <div class="homeTeamBottomPannelDivider"></div>
            <div class="homeTeamBottomPannelCard">
                <div class="homeTeamBottomPannelCardTopPannel">
                    <div class="homeTeamBottomPannelCardTopPannelImage"><img src="{{ asset('images/fennekin.png') }}" alt="Riolu combattant"></div>
                    <div class="homeTeamBottomPannelCardTopPannelTitle">{{ 'soutenez_votre_equipe'|trans({}, 'app') }}</div>
                </div>
                <div class="homeTeamBottomPannelCardBottomPannel">{{ 'soutenez_votre_equipe_description'|trans({}, 'app') }}</div>
            </div>
        </div>
    </div>

    <div class="separator"></div>

    <div class="homeExploration">
        <div class="homeExplorationLeftPannel">
            <img class="homeExplorationLeftPannelImage" src="{{ asset('images/colored-paysage.png') }}" alt="Paysage de Valtoria">
            <img class="homeExplorationLeftPannelTexture" src="{{ asset('texture/parchement-hole.png') }}">
        </div>
        <div class="homeExplorationRightPannel">
            <div class="homeExplorationRightPannelTitle">{{ 'explorez_les_contrees_de_valtoria'|trans({}, 'app') }}</div>
            <div class="homeExplorationRightPannelContent">
                <p>{{ 'explorez_les_contrees_de_valtoria_description_1'|trans({}, 'app') }}</p>
                <p>{{ 'explorez_les_contrees_de_valtoria_description_2'|trans({}, 'app') }}</p>
                <p>{{ 'explorez_les_contrees_de_valtoria_description_3'|trans({}, 'app') }}</p>
                <p>{{ 'explorez_les_contrees_de_valtoria_description_4'|trans({}, 'app') }}</p>
            </div>
            <div class="homeExplorationRightPannelImage">
                <img src="{{ asset('images/bulbizarre-aventurier.png') }}" alt="Bulbizarre aventurier">
                <img src="{{ asset('images/goupix-chapeau.png') }}" alt="Goupix avec son chapeau">
            </div>
        </div>
    </div>

    <div class="separator"></div>

    <div class="homeJoinExplorers">
        <div class="homeJoinExplorersTopPannel">
            <div class="homeJoinExplorersTopPannelTitle">{{ 'rejoignez_la_guilde_de_fort_ecorce'|trans({}, 'app') }}</div>
            <div class="homeJoinExplorersTopPannelContent">{{ 'rejoignez_la_guilde_de_fort_ecorce_description'|trans({}, 'app') }}</div>
        </div>
    </div>
    <div class="homeJoinExplorersBottomPannel">
        <img class="homeJoinExplorersBottomPannelImage" src="{{ asset('images/fort-ecorce.png') }}" alt="Fort-Écorce">
    </div>
{% endblock %}

{% block javascripts %}

{% endblock %}

Symfony/templates/newbase.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
        <title>{% block title %}PMD : Valtoria{% endblock %}</title>
        <link rel="icon" href="{{ asset('icons/valtoria.png') }}">

        <link rel="stylesheet" href="{{ asset('newbase.css') }}">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% include '_shared/_navbar.html.twig' %}
        {% block uppercontent %}{% endblock %}
        <div id='content'>
            {% block body %}{% endblock %}
        </div>
        {% block javascripts %}{% endblock %}
        
        <footer>
            <p>Valtoria  est un jeu web/discord aucunement lié à Nintendo. Tout les médias et designs conceptuels à (C) Nintendo 2023.Les personnages et images de Pokémon™ appartiennent à Pokémon USA, Inc. Ce site web n’est aucunement affilié ni approuvé par Nintendo, Creatures, GAMEFREAK, The Pokémon Company, Chunsoft, Pokémon USA, Inc ou Wizards of the coast</p>
        </footer>
    </body>
</html>